AllCops:
  Exclude:
    - db/**
    - config/**
    - script/**
Style/PredicateName:
  Exclude:
    - lib/resources/**
Metrics/LineLength:
  Exclude:
    - features/step_definitions/**
Documentation:
  Enabled: false
