require 'webmachine'
require 'jwt'
require 'roar/json/hal'
require 'sqlite3'
require 'sequel'

require 'resources/base_resource'
require 'resources/api_resource'
require 'resources/tokens_resource'
require 'resources/categories_resource'
require 'resources/category_resource'
require 'resources/articles_resource'
require 'resources/article_resource'
require 'resources/readers_resource'

require 'models/user'
require 'models/category'
require 'models/article'
require 'models/reader'

require 'representers/category_representer'
require 'representers/categories_representer'
require 'representers/article_representer'
require 'representers/articles_representer'
require 'representers/reader_representer'
require 'representers/readers_representer'
